### ISSUE TITLE
Ya'll  need to act like grown  folks

### ISSUE THREAD

**Issue by The-Phoneboy** [nanoscopic/controlfloor#28]
This gonna take a minute...in your best interest to read it..
-------------------------------------------------------------------------------------------------------------------------------------------------
rewind == 2 +months ago I found STF/Devicefarmer   &&  the contolfloor
opened up...disclosed more about self the normal....as I was impressed and want in....missed it? .there is   an issue somewhere..

-------------------------------------------------------------------------------------------------------------------------------------------------

refresh----I'm a systems guy...no code skills....tried..failed..don't care...don't roll up in my kool aid with your hardware prowess... I will shut you down....

wtf is that..I was there
![image](https://user-images.githubusercontent.com/43960406/119357230-f05c4200-bc6c-11eb-8441-b1e78cb2ba98.png)

if your code  does  is broken I can't fix it...that being said...Jesus Himself taught  me to troubleshoot and debug...logs never lie...i can read.....tracking down issues for ya'll to fix.. my Jam 

----------------------------------------------------------------------------------------------------------------------------------------------
**anything that can go wrong --will happen to me
if anyone can fuck it ..i will be first**

I make up for my shortcoming with persistence ....I take the time to read and give it a bash first...no such thing as a dumb question or admitting you have no clue...google is your  friend...try.....

--------------------------------------------------------------------------------------------------------------------------------------------
know your role

![image](https://user-images.githubusercontent.com/43960406/119370506-f3f6c580-bc7a-11eb-9f78-f3116bda22da.png)
 

my crap-----more crap coming to make it  purdy

---------------------------------------------------------------------------------------------------------------------------------------------

**REALITY CHECK**  **UNBIASED NEW GUY OBSERVATIONS** **I DON'T CARE IF YOU AGREE OR APPROVE**

STF IS DEAD

DEVICEFARMER IS DEAD

LONG LIVE NANOSCOPIC

---------------------------------------------------------------------------------------------------------------------------------------------

WHY

--------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------------------------
STF--

![image](https://user-images.githubusercontent.com/43960406/119369901-4f748380-bc7a-11eb-841e-cacded785b67.png)

DeviceFarmer--

![image](https://user-images.githubusercontent.com/43960406/119369988-64511700-bc7a-11eb-84c1-2158d9cf6635.png)

nanoscopic--
![image](https://user-images.githubusercontent.com/43960406/119370146-94001f00-bc7a-11eb-95ab-3822f2d595c2.png)

contributors??  wtf

----------------------------------------------------------------------------------------------------------------------------------------

insert mumbling for you all about me

-------------------------------------------------------------------------------------------------------------------------------------------

maybe i have one fuck to give

------------------------------------------------------------------------------------------------------------------------------------------

**FINALLY MY FUCKING POINT'S**
-----------------------------------------------------------------------------------------------------------------------------------------
@nanoscopic  is  a sharp cookie..seems he is the only one working to me..20 mins with google.....he is all over the place.......

his work can be our work...or..in my  professional opinion

** he will say fuck this and teach basket weaving
** he will face the inevitable and sell it to finance progress (closer than you think)
**someone else will do it better..boat missed.... weep...opportunity of a lifetime has vanished

----------------------------------------------------------------------------------------------------------------------------------------------
**CHOICES**

Quit
Just do it

---------------------------------------------------------------------------------------------------------------------------------------------

love me--hate me ---slag me --ridicule---i give two  fucks--my balls are bigger than yours--i will survive

---------------------------------------------------------------------------------------------------------------------------------------------

“Gas, Grass, or Ass — No one Rides for Free.”  ** Biker's on Drugs

"Lead Follow or Get Out of the Way"  Ted Turner  **LEGEND** 

"Are we Mice or Are we Men?"  Dr. Seuss --wtf--seriously

--------------------------------------------------------------------------------------------------------------------------------------------

**insert theme song for rant**  all out of apologies  
https://www.youtube.com/watch?v=ny14OCGQo9E

@nanoscopic  please consider this my resume 

p.s.

![image](https://user-images.githubusercontent.com/43960406/119373097-aa5baa00-bc7d-11eb-839d-50becd45d83a.png)

sometimes....truth is stranger than fiction---bad religion

**Comment by nanoscopic** [comment]
I'll accept this as a vouch for my ability to continue to move the project forward.

I would like to caution against excessive dismissal of STF or DeviceFarmer though.

STF was originally released by Headspin, and has many fans/users. Headspin refused/refuses to accept iOS related commits, and is anti-open source in recent time due to being controlled by investors in recent times. As a result, I have been somewhat vocally opposed to Headspin. A number of other community members have also expressed some displeasure with Headspin leadership.

That all led to the creation of the DeviceFarmer fork. It is also due to Headspin mostly abandoning the project and leaving contributors alone to care for STF.

Despite the way Headspin has acted badly in recent years, they did originally release the project as open source and that did spawn years of interest in this work, including the projects I have been working on. As a result, Headspin should still be respected to some degree for that.

More so, the STF project continues to have users, and I don't wish to be divisive to the community. I only wish to make a better path forward.

DeviceFarmer has been slow to advance, but is still necessary at this time, as there are a variety of users who want to continue to use STF and have iOS support as well. Additionally, there aren't any real equivalent open source device farm projects for Android, and I have not yet begun adding Android support to ControlFloor.

I don't myself have much time to contribute to DeviceFarmer currently, but I do believe it should be maintained and kept functional as well as possible till a time that something better ( ControlFloor? ) can replace it.

DeviceFarmer is a young project. It's planning and method of keeping contribution alive is still in flux. I dislike the core code of it, as I have long been critical of NodeJS based projects, but all contributors to it, and those who work with it and want to use it should be respected.

Regardless of any personal dislike for DeviceFarmer codebase on my part, respect for those in the project and struggling to keep it working well must exist.

My goal overall with ControlFloor is in fact to become the prominent open source device farm project, but that cannot be done by being rude or offensive to those who continue to contribute to the open source device farm arena by way of other projects. There should be open cooperation between all, and acceptance of the many and varied views of others.

Thank you for your desire to work with and help this project. I will continue to strive to make it possible for that to occur.

Your message here is somewhat course, but you are welcome to contribute and work together to bring about a better future.

One last note; I am not sure how this is an issue and what exactly you would like to happen for this issue to be resolved. Could you clarify if there is some result you want from this issue?

**Comment by The-Phoneboy** [comment]
Yes Sir….will just not mention it again…no offense meant…I am rattling cages….I want this to succeed
…I           will not apologize for my  thoughts…honesty is always the best…I am indeed coarse..raw..unfiltered…you love me or hate me. ..I’ll be damned if not respected…
some of that was piss and vinegar…..staking out my turf….a challenge…
I was trained Sir…from an early age….walk in like you own the place and most get out of the way..
Establish yourself  with authority


You never get a second chance to make a first impression…that was my second salvo..my first was more obsequious than my nature
..

The Pandemic is destroying  India

https://www.bbc.com/news/world-asia-57224565

it is a dangerous  time to invest heavily there

that being said I have people I trust mobile developer who produce

I  have no mind to take advantage of the situation

 I am not rich…but not without resources

US$ in small amounts can feed families

Thank you sincerely for accepting me…I will do my part..

We find  form recruit at a time

This is the way



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
