### ISSUE TITLE
Can't start cfa

### ISSUE THREAD

**Issue by binhdao112** [nanoscopic/controlfloor#35]
Hi! I'm trying to start controlfloor, however, i have found this issue:
"Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64"

Is controlfloor just start on chip arm64(Apple Chip M1 or Apple Chip M2)?
Can anybody help me please 💯 💯

**Comment by Sin-Nguyen** [comment]
I facing same issue . @nanoscopic  Do you know any ways to fix it ?

**Comment by nanoscopic** [comment]
WDA/CFA cannot be built with tweaks the configuration of the build on newer versions of Xcode due to restrictions Apple added.

You can still do it with the appropriate tweak. I mentioned this in another issues on this same repo. I am intentionally not sharing the details as I already gave hints to how to do this.

This is an unmaintained old version of controlfloor. It is over a year out of date now if I recall right. Many fixes and improvements have been made but they are closed source.

I've said a bunch of times that I welcome anyone to attempt to maintain this, but it cannot be done without serious effort. That costs money. People weren't sponsoring the open source project adequately, and companies were just using this without giving back. It had to go closed-source for the time being to ensure it's development can continue.

Seeing as how since I closed-sourced this project basically no one has contributed any fixes, and people only ever ask me questions ( which I'm not motivated to answer as it would then compete with my own companies offering ), I'm not sure what you are all expecting.

I know how to fix it yes. I'm not sharing it because it isn't readily known. If you go digging through WebDriverAgent issues ( currently maintained by Appium ) the information you need to correct this problem is buried in there.
